### PR TITLE
Ja emojipicker

### LINKED ISSUE #25: Emoji picking

### PR DESCRIPTION
**Pull request by johnachor**
closes #25

### CODE REVIEW

**Comment by johnachor** [comment]
Note that everyone will need to do a new "npm install" in their lib folder in order to grab the packages I changed out.

**Comment by ASlayton** [comment]
Have all of the script tags been moved to the beginning of the document? Shouldn't they be left at the bottom of the page?

**Review by ASlayton — APPROVED** [review]

**Comment by johnachor** [comment]
The app.js script tag is still at the bottom, but all the prereq css and javascript has been moved into the header.  This was so I could make sure there were no duplicates and get everything in the right order.

**Comment by amillion3** [comment]
Looks good to me! 👍

**Pull request merged**
